package com.pmm.pickmymenu_back.global;

import com.pmm.pickmymenu_back.domain.FoodTree;
import com.pmm.pickmymenu_back.domain.Member;
import com.pmm.pickmymenu_back.repository.FoodTreeRepository;
import com.pmm.pickmymenu_back.repository.MemberRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

@Component
@Transactional
@RequiredArgsConstructor
public class CustomRunner implements ApplicationRunner {

    private final FoodTreeRepository foodTreeRepository;
    private final MemberRepository memberRepository;

    @Override
    public void run(ApplicationArguments args) throws Exception {
//        Member member = Member.create("nowcow", "최현우",
//                "$2a$10$R1sOsCTIiyZi7kMX8cCxYusRF2o1bzF1Si.mmlq1oK1es26F7Pcwq", "nowcow@a.com",
//                "920514", "01041436250", "남자");
//        Member member1 = Member.create("testUser", "홍길동",
//                "$2a$10$ToYeHTarnkESA5ynNfM6T.WqMOmRh3nSKTULBFPBtR05GSKFb0UpC",
//                "testuser@example.com", "1990-01-01", "010-1234-5678", "남자");
//        Member member2 = Member.create("cha12", "차성환",
//                "$2a$10$OieXv5NMFx37TIP0xvnfRuBCb8OuHuoMWi05fK6ocsjPTK7B.avom", "cha1234@naver.com",
//                "19980415", "01012345678", "남자");
//
//        memberRepository.save(member);
//        memberRepository.save(member1);
//        memberRepository.save(member2);
//
//        FoodTree foodTree1 = FoodTree.create( "굽기",	1, null);
//        FoodTree foodTree2 = FoodTree.create( "기타",	1, null);
//        FoodTree foodTree3 = FoodTree.create( "끓이기", 	1, null);
//        FoodTree foodTree4 = FoodTree.create( "데치기", 	1, null);
//        FoodTree foodTree5 = FoodTree.create( "무침",	1, null);
//        FoodTree foodTree6 = FoodTree.create( "볶음",	1, null);
//        FoodTree foodTree7 = FoodTree.create( "부침",	1, null);
//        FoodTree foodTree8 = FoodTree.create( "비빔",	1, null);
//        FoodTree foodTree9 = FoodTree.create( "삶기",	1, null);
//        FoodTree foodTree10 = FoodTree.create( "절임",	1, null);
//        FoodTree foodTree11 = FoodTree.create( "조림",	1, null);
//        FoodTree foodTree12 = FoodTree.create( "찜",	1, null);
//        FoodTree foodTree13 = FoodTree.create( "튀김",	1, null);
//        FoodTree foodTree14 = FoodTree.create( "회",	1, null);
//
//        foodTreeRepository.save(foodTree1);
//        foodTreeRepository.save(foodTree2);
//        foodTreeRepository.save(foodTree3);
//        foodTreeRepository.save(foodTree4);
//        foodTreeRepository.save(foodTree5);
//        foodTreeRepository.save(foodTree6);
//        foodTreeRepository.save(foodTree7);
//        foodTreeRepository.save(foodTree8);
//        foodTreeRepository.save(foodTree9);
//        foodTreeRepository.save(foodTree10);
//        foodTreeRepository.save(foodTree11);
//        foodTreeRepository.save(foodTree12);
//        foodTreeRepository.save(foodTree13);
//        foodTreeRepository.save(foodTree14);
//
//        FoodTree foodTree15 = FoodTree.create( "디저트",	2, 	foodTree1);
//        FoodTree foodTree16 = FoodTree.create( "만두",	2, 	foodTree1);
//        FoodTree foodTree17 = FoodTree.create( "면",	2, 	foodTree1);
//        FoodTree foodTree18 = FoodTree.create( "밥",	2, 	foodTree1);
//        FoodTree foodTree19 = FoodTree.create( "빵",	2, 	foodTree1);
//        FoodTree foodTree20 = FoodTree.create( "샐러드",	2, 	foodTree1);
//        FoodTree foodTree22 = FoodTree.create( "양식",	2, 	foodTree1);
//        FoodTree foodTree25 = FoodTree.create( "디저트",	2, 	foodTree2);
//        FoodTree foodTree26 = FoodTree.create( "만두",	2, 	foodTree2);
//        FoodTree foodTree27 = FoodTree.create( "면",	2, 	foodTree2);
//        FoodTree foodTree28 = FoodTree.create( "밥",	2, 	foodTree2);
//        FoodTree foodTree29 = FoodTree.create( "빵",	2, 	foodTree2);
//        FoodTree foodTree30 = FoodTree.create( "스프",	2, 	foodTree2);
//        FoodTree foodTree31 = FoodTree.create( "양식",	2, 	foodTree2);
//        FoodTree foodTree32 = FoodTree.create( "찌개",	2, 	foodTree2);
//        FoodTree foodTree33 = FoodTree.create( "국/탕",	2,	foodTree3);
//        FoodTree foodTree34 = FoodTree.create( "디저트",	2, 	foodTree3);
//        FoodTree foodTree35 = FoodTree.create( "만두",	2, 	foodTree3);
//        FoodTree foodTree36 = FoodTree.create( "면",	2, 	foodTree3);
//        FoodTree foodTree37 = FoodTree.create( "밥",	2, 	foodTree3);
//        FoodTree foodTree38 = FoodTree.create( "샐러드",	2, 	foodTree3);
//        FoodTree foodTree39 = FoodTree.create( "스프",	2, 	foodTree3);
//        FoodTree foodTree40 = FoodTree.create( "양식",	2, 	foodTree3);
//        FoodTree foodTree41 = FoodTree.create( "죽",	2, 	foodTree3);
//        FoodTree foodTree42 = FoodTree.create( "찌개",	2, 	foodTree3);
//        FoodTree foodTree43 = FoodTree.create( "만두",	2, 	foodTree4);
//        FoodTree foodTree44 = FoodTree.create( "면",	2, 	foodTree4);
//        FoodTree foodTree45 = FoodTree.create( "샐러드",	2, 	foodTree4);
//        FoodTree foodTree46 = FoodTree.create( "스프",	2, 	foodTree4);
//        FoodTree foodTree47 = FoodTree.create( "양식",	2, 	foodTree4);
//        FoodTree foodTree48 = FoodTree.create( "디저트",	2, 	foodTree5);
//        FoodTree foodTree49 = FoodTree.create( "만두",	2, 	foodTree5);
//        FoodTree foodTree50 = FoodTree.create( "면",	2, 	foodTree5);
//        FoodTree foodTree51 = FoodTree.create( "밥",	2, 	foodTree5);
//        FoodTree foodTree52 = FoodTree.create( "샐러드",	2, 	foodTree5);
//        FoodTree foodTree53 = FoodTree.create( "스프",	2, 	foodTree5);
//        FoodTree foodTree54 = FoodTree.create( "양식",	2, 	foodTree5);
//        FoodTree foodTree56 = FoodTree.create( "디저트",	2, 	foodTree6);
//        FoodTree foodTree57 = FoodTree.create( "만두",	2, 	foodTree6);
//        FoodTree foodTree58 = FoodTree.create( "면",	2, 	foodTree6);
//        FoodTree foodTree59 = FoodTree.create( "밥",	2, 	foodTree6);
//        FoodTree foodTree60 = FoodTree.create( "샐러드",	2, 	foodTree6);
//        FoodTree foodTree61 = FoodTree.create( "스프",	2, 	foodTree6);
//        FoodTree foodTree62 = FoodTree.create( "양식",	2, 	foodTree6);
//        FoodTree foodTree63 = FoodTree.create( "죽",	2, 	foodTree6);
//        FoodTree foodTree65 = FoodTree.create( "디저트",	2, 	foodTree7);
//        FoodTree foodTree66 = FoodTree.create( "만두",	2, 	foodTree7);
//        FoodTree foodTree67 = FoodTree.create( "면",	2, 	foodTree7);
//        FoodTree foodTree68 = FoodTree.create( "밥",	2, 	foodTree7);
//        FoodTree foodTree69 = FoodTree.create( "샐러드",	2, 	foodTree7);
//        FoodTree foodTree70 = FoodTree.create( "양식",	2, 	foodTree7);
//        FoodTree foodTree71 = FoodTree.create( "찌개",	2, 	foodTree7);
//        FoodTree foodTree72 = FoodTree.create( "디저트",	2, 	foodTree8);
//        FoodTree foodTree73 = FoodTree.create( "만두",	2, 	foodTree8);
//        FoodTree foodTree74 = FoodTree.create( "면",	2, 	foodTree8);
//        FoodTree foodTree75 = FoodTree.create( "밥",	2, 	foodTree8);
//        FoodTree foodTree76 = FoodTree.create( "샐러드",	2, 	foodTree8);
//        FoodTree foodTree77 = FoodTree.create( "양식",	2, 	foodTree8);
//        FoodTree foodTree78 = FoodTree.create( "국/탕",	2,	foodTree9);
//        FoodTree foodTree79 = FoodTree.create( "디저트",	2, 	foodTree9);
//        FoodTree foodTree80 = FoodTree.create( "만두",	2, 	foodTree9);
//        FoodTree foodTree81 = FoodTree.create( "면",	2, 	foodTree9);
//        FoodTree foodTree82 = FoodTree.create( "밥",	2, 	foodTree9);
//        FoodTree foodTree83 = FoodTree.create( "샐러드",	2, 	foodTree9);
//        FoodTree foodTree84 = FoodTree.create( "스프",	2, 	foodTree9);
//        FoodTree foodTree85 = FoodTree.create( "양식",	2, 	foodTree9);
//        FoodTree foodTree86 = FoodTree.create( "죽",	2, 	foodTree9);
//        FoodTree foodTree88 = FoodTree.create( "디저트",	2, 	foodTree10);
//        FoodTree foodTree89 = FoodTree.create( "만두",	2, 	foodTree10);
//        FoodTree foodTree90 = FoodTree.create( "면",	2, 	foodTree10);
//        FoodTree foodTree91 = FoodTree.create( "밥",	2, 	foodTree10);
//        FoodTree foodTree92 = FoodTree.create( "샐러드",	2, 	foodTree10);
//        FoodTree foodTree93 = FoodTree.create( "양식",	2, 	foodTree10);
//        FoodTree foodTree94 = FoodTree.create( "국/탕",	2,	foodTree11);
//        FoodTree foodTree95 = FoodTree.create( "디저트",	2, 	foodTree11);
//        FoodTree foodTree96 = FoodTree.create( "만두",	2, 	foodTree11);
//        FoodTree foodTree97 = FoodTree.create( "면",	2, 	foodTree11);
//        FoodTree foodTree98 = FoodTree.create( "샐러드",	2, 	foodTree11);
//        FoodTree foodTree99 = FoodTree.create( "스프",	2, 	foodTree11);
//        FoodTree foodTree100 = FoodTree.create( "양식",	2, 	foodTree11);
//        FoodTree foodTree101 = FoodTree.create( "찌개",	2, 	foodTree11);
//        FoodTree foodTree103 = FoodTree.create( "디저트",	2, 	foodTree12);
//        FoodTree foodTree104 = FoodTree.create( "만두",	2, 	foodTree12);
//        FoodTree foodTree105 = FoodTree.create( "면",	2, 	foodTree12);
//        FoodTree foodTree106 = FoodTree.create( "밥",	2, 	foodTree12);
//        FoodTree foodTree107 = FoodTree.create( "샐러드",	2, 	foodTree12);
//        FoodTree foodTree108 = FoodTree.create( "스프",	2, 	foodTree12);
//        FoodTree foodTree109 = FoodTree.create( "양식",	2, 	foodTree12);
//        FoodTree foodTree111 = FoodTree.create( "디저트",	2, 	foodTree13);
//        FoodTree foodTree112 = FoodTree.create( "만두",	2, 	foodTree13);
//        FoodTree foodTree113 = FoodTree.create( "면",	2, 	foodTree13);
//        FoodTree foodTree114 = FoodTree.create( "빵",	2, 	foodTree13);
//        FoodTree foodTree115 = FoodTree.create( "샐러드",	2, 	foodTree13);
//        FoodTree foodTree116 = FoodTree.create( "스프",	2, 	foodTree13);
//        FoodTree foodTree117 = FoodTree.create( "양식",	2, 	foodTree13);
//        FoodTree foodTree118 = FoodTree.create( "국/탕", 	2	,foodTree14);
//        FoodTree foodTree119 = FoodTree.create( "면",	2, 	foodTree14);
//        FoodTree foodTree120 = FoodTree.create( "샐러드",	2, 	foodTree14);
//        FoodTree foodTree121 = FoodTree.create( "양식",	2, 	foodTree14);
//        foodTreeRepository.save(foodTree15);
//        foodTreeRepository.save(foodTree16);
//        foodTreeRepository.save(foodTree17);
//        foodTreeRepository.save(foodTree18);
//        foodTreeRepository.save(foodTree19);
//        foodTreeRepository.save(foodTree20);
//        foodTreeRepository.save(foodTree22);
//        foodTreeRepository.save(foodTree25);
//        foodTreeRepository.save(foodTree26);
//        foodTreeRepository.save(foodTree27);
//        foodTreeRepository.save(foodTree28);
//        foodTreeRepository.save(foodTree29);
//        foodTreeRepository.save(foodTree30);
//        foodTreeRepository.save(foodTree31);
//        foodTreeRepository.save(foodTree32);
//        foodTreeRepository.save(foodTree33);
//        foodTreeRepository.save(foodTree34);
//        foodTreeRepository.save(foodTree35);
//        foodTreeRepository.save(foodTree36);
//        foodTreeRepository.save(foodTree37);
//        foodTreeRepository.save(foodTree38);
//        foodTreeRepository.save(foodTree39);
//        foodTreeRepository.save(foodTree40);
//        foodTreeRepository.save(foodTree41);
//        foodTreeRepository.save(foodTree42);
//        foodTreeRepository.save(foodTree43);
//        foodTreeRepository.save(foodTree44);
//        foodTreeRepository.save(foodTree45);
//        foodTreeRepository.save(foodTree46);
//        foodTreeRepository.save(foodTree47);
//        foodTreeRepository.save(foodTree48);
//        foodTreeRepository.save(foodTree49);
//        foodTreeRepository.save(foodTree50);
//        foodTreeRepository.save(foodTree51);
//        foodTreeRepository.save(foodTree52);
//        foodTreeRepository.save(foodTree53);
//        foodTreeRepository.save(foodTree54);
//        foodTreeRepository.save(foodTree56);
//        foodTreeRepository.save(foodTree57);
//        foodTreeRepository.save(foodTree58);
//        foodTreeRepository.save(foodTree59);
//        foodTreeRepository.save(foodTree60);
//        foodTreeRepository.save(foodTree61);
//        foodTreeRepository.save(foodTree62);
//        foodTreeRepository.save(foodTree63);
//        foodTreeRepository.save(foodTree65);
//        foodTreeRepository.save(foodTree66);
//        foodTreeRepository.save(foodTree67);
//        foodTreeRepository.save(foodTree68);
//        foodTreeRepository.save(foodTree69);
//        foodTreeRepository.save(foodTree70);
//        foodTreeRepository.save(foodTree71);
//        foodTreeRepository.save(foodTree72);
//        foodTreeRepository.save(foodTree73);
//        foodTreeRepository.save(foodTree74);
//        foodTreeRepository.save(foodTree75);
//        foodTreeRepository.save(foodTree76);
//        foodTreeRepository.save(foodTree77);
//        foodTreeRepository.save(foodTree78);
//        foodTreeRepository.save(foodTree79);
//        foodTreeRepository.save(foodTree80);
//        foodTreeRepository.save(foodTree81);
//        foodTreeRepository.save(foodTree82);
//        foodTreeRepository.save(foodTree83);
//        foodTreeRepository.save(foodTree84);
//        foodTreeRepository.save(foodTree85);
//        foodTreeRepository.save(foodTree86);
//        foodTreeRepository.save(foodTree88);
//        foodTreeRepository.save(foodTree89);
//        foodTreeRepository.save(foodTree90);
//        foodTreeRepository.save(foodTree91);
//        foodTreeRepository.save(foodTree92);
//        foodTreeRepository.save(foodTree93);
//        foodTreeRepository.save(foodTree94);
//        foodTreeRepository.save(foodTree95);
//        foodTreeRepository.save(foodTree96);
//        foodTreeRepository.save(foodTree97);
//        foodTreeRepository.save(foodTree98);
//        foodTreeRepository.save(foodTree99);
//        foodTreeRepository.save(foodTree100);
//        foodTreeRepository.save(foodTree101);
//        foodTreeRepository.save(foodTree103);
//        foodTreeRepository.save(foodTree104);
//        foodTreeRepository.save(foodTree105);
//        foodTreeRepository.save(foodTree106);
//        foodTreeRepository.save(foodTree107);
//        foodTreeRepository.save(foodTree108);
//        foodTreeRepository.save(foodTree109);
//        foodTreeRepository.save(foodTree111);
//        foodTreeRepository.save(foodTree112);
//        foodTreeRepository.save(foodTree113);
//        foodTreeRepository.save(foodTree114);
//        foodTreeRepository.save(foodTree115);
//        foodTreeRepository.save(foodTree116);
//        foodTreeRepository.save(foodTree117);
//        foodTreeRepository.save(foodTree118);
//        foodTreeRepository.save(foodTree119);
//        foodTreeRepository.save(foodTree120);
//        foodTreeRepository.save(foodTree121);

    }
}
